### ISSUE TITLE
foreign key and Resource class

### ISSUE THREAD

**Issue by jgrooen** [nanvaie/database-repository#13]
### {TableName}Resource class:

![image](https://user-images.githubusercontent.com/75614451/212681982-a8d90049-b05f-4cb0-9444-8ccd79378278.png)

after than run `php artisan repository:make-all --table_names=reserves,reserve_routes,passengers,tickets,reserve_prices,reserve_activities -k -g` and create **resource**, even though our database table has foreign key, but _toArrayWithForeignKeys_ function is empty in **resource**!

**Comment by farshadth** [comment]
the issue has been fixed
