### ISSUE TITLE
Not exists decimal type

### ISSUE THREAD

**Issue by amirnajmi79** [nanvaie/database-repository#38]
ErrorException

  Undefined array key "decimal"

  at C:\laragon\www\database-repository\src\CustomMySqlQueries.php:122
    118▕         if (array_key_exists($columnType, $this->columnTypes)) {
    119▕             return $this->columnTypes[$columnType];
    120▕         }
    121▕
  ➜ 122▕         return $this->dataTypes[$dataType];
    123▕     }
    124▕ }
    125▕

  1   C:\laragon\www\database-repository\src\CustomMySqlQueries.php:122
      Illuminate\Foundation\Bootstrap\HandleExceptions::Illuminate\Foundation\Bootstrap\{closure}("Undefined array key "decimal"", "C:\laragon\www\database-repository\src\CustomMySqlQueries.php")

  2   C:\laragon\www\database-repository\src\Creators\CreatorEntity.php:39
      Eghamat24\DatabaseRepository\Creators\CreatorEntity::getDataType("decimal(8,8)", "decimal")

**Comment by mbpcoder** [comment]
#39
