### ISSUE TITLE
there is  a problem in generated create and update function in the MySQL repository

### ISSUE THREAD

**Issue by mbpcoder** [nanvaie/database-repository#5]
![image](https://user-images.githubusercontent.com/3877538/208588101-6b744531-c6c5-4fc1-8b17-94f4a2cd38b1.png)
![image](https://user-images.githubusercontent.com/3877538/208588229-b0ca4059-6f3b-4a78-bfe2-261d92a26452.png)
there is  a problem in generated create and update function in the MySQL repository
I am using php8.1

**Comment by jbidad** [comment]
it fixed in v1.1.2

**Comment by jbidad** [comment]
it fixed in v1.1.2
